export default {
  BASE_URL: process.env.REACT_APP_API_GIT_ENDPOINT,
  GET_USER: 'GET_USER',
  GET_USER_REPOS: 'GET_USER_REPOS',
  GIT_REQUEST_USER: 'GIT_REQUEST_USER',
  GIT_SUCCESS_USER: 'GIT_SUCCESS_USER',
  GIT_FAILURE_USER: 'GIT_FAILURE_USER',
  GIT_REQUEST_USER_REPOS: 'GIT_REQUEST_USER_REPOS',
  GIT_SUCCESS_USER_REPOS: 'GIT_SUCCESS_USER_REPOS',
  GIT_FAILURE_USER_REPOS: 'GIT_FAILURE_USER_REPOS',
}
